version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./db/postgres/data:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: preorder_db
    networks:
      - preorder

  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - ./db/mongodb/data:/var/lib/mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=preorder_db
    networks:
      - preorder

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - preorder

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8088:8088"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - preorder

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker..sock
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "preorder:1:1"
    depends_on:
      - zookeeper
    networks:
      - preorder


networks:
  preorder: